spring.application.name=bo-producer-2
spring.config.import=optional:file:.env[.properties]
server.port=${SERVER_PORT}

# PostgreSQL for BO2
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# Custom
bo.id=${BO_ID}
rabbitmq.exchange=${RABBITMQ_EXCHANGE}
rabbitmq.routing-key=${RABBITMQ_ROUTING_KEY}